### ISSUE TITLE
Display media attachments in Inbox

### ISSUE THREAD

**Issue by Shukuyen** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#1]
Good job on the inbox!

One feature request after initial testing: 
Display media attachments sent with the push message in the inbox list.

**Comment by wfhm** [comment]
Hi,

Thank you for your suggestion! This indeed sounds like a great feature, however for iOS it would require quite a big changes both on our backend and in SDK, so, most probably this feature will not be implemented in the nearest future. I have put this feature in our backlog, so once it is done I will update this thread.

**Comment by wfhm** [comment]
This functionality is finally delivered with 5.16.0 release.

**Comment by Shukuyen** [comment]
The latest release on Github is 5.8, can you help me find the release notes for 5.16? Thanks!
