### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by frederic-c-dcode** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#5]
There is a warning saying

===========================

Attention: PushwooshInboxUI version (v5.8.6) is different from Pushwoosh SDK version (v5.13.0). There might be compatibility issues.

===========================

Maybe you should update PushwooshInboxUI to match the latest version of Pushwoosh SDK.

**Comment by wfhm** [comment]
@frederic-c-dcode Fixed with the latest release.
