### ISSUE TITLE
Observer for PWInbox.unreadMessagesCount

### ISSUE THREAD

**Issue by Chopyhoo** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#6]
Hi, I'm developing an app which has unread messages badge in several places and the way to update the value of it is not very great. It would be easer and better if PWInbox could notify when PWInbox.unreadMessagesCount is changed. 

Could you please add an observable that fires a notification when PWInbox.unreadMessagesCount is changed? For example, when user receives new mail or marks it as read.

**Comment by wfhm** [comment]
Hi @Chopyhoo,

Let me first consult our team regarding this solution.

I will update you as soon as there is any news.

**Comment by wfhm** [comment]
Hey @Chopyhoo,

I have consulted my colleagues and as a result, I am glad to inform you that we will add this functionality soon. I am not able to provide the exact ETA at the moment, however, I will update you as soon as the job is done.

Stay tuned!

**Comment by Chopyhoo** [comment]
Thank you!

**Comment by wfhm** [comment]
@Chopyhoo,

Added with the latest release.
