### ISSUE TITLE
Crash: Could not cast value of type 'PWInboxMessageInternal' to 'NSString'

### ISSUE THREAD

**Issue by Chopyhoo** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#7]
Hi!

Inbox UI crashes when deleting push from inbox

```
Could not cast value of type 'PWInboxMessageInternal' (0x104cfe6b0) to 'NSString' (0x1fefa9ab8).
2019-12-02 17:30:34.746401+0300 Application[7286:5465467] Could not cast value of type 'PWInboxMessageInternal' (0x104cfe6b0) to 'NSString' (0x1fefa9ab8).
```

**Comment by wfhm** [comment]
Hi @Chopyhoo,

May I ask you to specify the version of the Pushwoosh-iOS SDK you are using at the moment and the entire console log from the device showing the application launch and the moment of the crash itself?

What are the steps to reproduce?

**Comment by Chopyhoo** [comment]
PushwooshInboxUI (5.16.0)

Preconditions:
Some class must be added as observer in PWInbox, using method in PWInbox.h:
```
+ (id<NSObject>)addObserverForUpdateInboxMessagesCompletion:(void (^)(NSArray<NSString *> *messagesDeleted,
                                                                      NSArray<NSObject<PWInboxMessageProtocol> *> *messagesAdded,
                                                                      NSArray<NSObject<PWInboxMessageProtocol> *> *messagesUpdated))completion;
```

Steps to reproduce:

1. Open inbox with at least 1 message in it.
2. Swipe the message cell to the left until the red delete button appears
3. Tap delete button

Result: Crash with log:
```
Could not cast value of type 'PWInboxMessageInternal' (0x104cfe6b0) to 'NSString' (0x1fefa9ab8).
2019-12-02 17:30:34.746401+0300 Application[7286:5465467] Could not cast value of type 'PWInboxMessageInternal' (0x104cfe6b0) to 'NSString' (0x1fefa9ab8).
```

I wasn't using any of the variables in completion, my code looks this:
```
    private func addInboxObserver() {
        PWInbox.addObserver { [weak self] (_, _, _) in
            self?.checkUnreadMessagesCount()
        }
    }
```

**Comment by wfhm** [comment]
@Chopyhoo,

Thanks, will check this!

**Comment by wfhm** [comment]
@Chopyhoo,

Could you please update the version of the Pushwoosh-iOS SDK to the latest one and let me know about the result? This should fix this issue

https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/5.20.0

**Comment by Chopyhoo** [comment]
No crash in 5.20.0. Thank you!
