### ISSUE TITLE
Allow customization of table cell background color

### ISSUE THREAD

**Issue by Shukuyen** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#8]
We are implementing support for dark mode at the moment and the one thing we are not able to customize accordingly in PushwooshInboxUI is the row background color of each notification.
Would it be possible to expose the table view cell background color for customization in `PWIInboxStyle`?

**Comment by wfhm** [comment]
Hi @Shukuyen,

Could you please clarify what you mean by the row background color? There is a `backgroundColor` parameter which allows setting a cell background color, could it be the one you are looking for?

**Comment by Shukuyen** [comment]
The backgroundColor parameter controls the background color of the table view/view controller, if I am not mistaken. The cell I am talking about is this: https://github.com/Pushwoosh/pushwoosh-inbox-ui-ios-sdk/blob/7d649cabdb54c07b39e264f964a0e45088a2cae9/PushwooshInboxUI/PushwooshInboxUI/ViewControllers/PWIInboxMessageViewCell.m

This cell background stays white which doesn't look good in dark mode. We would like to adjust that color like we can do with other colors. Hope that clears it up, if not let me know and I can provide a  screenshot. Thanks!

**Comment by wfhm** [comment]
@Shukuyen,

Thanks for the clarification! Please let me pull some time to check it, I will be back as soon as there is any news.

**Comment by wfhm** [comment]
@Shukuyen,

Just tested the `backgroundColor`​ parameter, and it changes both the cell and the background colors, and it also works in Dark mode. Here is the quick example of how it looks like:

​ ![](https://pushwoosh.zendesk.com/attachments/token/qQtJjifu40qlBi8zStdazyZzw/?name=IMG_9202B1CB79D1-1.jpeg)​
Is that the behavior you want to achieve?

**Comment by stoyloff** [comment]
Yes, that is the behavior we are aiming for.
We actually do currently make use of the background property; but without the results you are achieving.

We are using a dynamic color that has a specific color for the light and one for the dark mode. But passing said color to the background property leaves us with dazzling whites when using the dark mode.

To be a little more specific: The background color will change only for the background, but not for the cells.

**Comment by wfhm** [comment]
@stoyloff,

The background color in inbox example from my last message was set with the following code:

    PWIInboxStyle *style = [PWIInboxStyle defaultStyle];
    UIColor *color = [UIColor colorNamed:@"Color"];
    style.backgroundColor = color;
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:[PWIInboxUI createInboxControllerWithStyle:style]];

Could you please try it and let me know about the results?

**Comment by stoyloff** [comment]
I am using the Swift equivalent of your code.

I am creating a PWIInboxStyle, configure the colors of it and then create a PWIInboxUI.createInboxController with said style.

When I change the background color to something like red, only the background if the ViewControllers view is changed to red, but the cells' background is untouched.

I don't have the access to the PWIInboxMessageViewCell, but debugging the view hierarchy clearly shows that the cells have the color white, while the background of the TableView is transparent, and the VC's view background color is the color I set it to.

**Comment by wfhm** [comment]
@stoyloff thank you for sharing the details. Just to make sure we are not missing anything, could you please share your Swift code and we will investigate it further?

**Comment by stoyloff** [comment]
I tried initializing with the default style instead of the custom style as well.

```
func inboxViewController() -> PWIInboxViewController? {
        
        let inboxStyle = PWIInboxStyle.customStyle(withDefaultImageIcon: nil,
                                                   textColor: Colors.Text.black,
                                                   accentColor: Colors.blue,
                                                   font: UIFont(name: "OpenSans", size: 15.0))
        
        inboxStyle?.titleColor = Colors.blue
        inboxStyle?.backgroundColor = Colors.Background.primary
        inboxStyle?.descriptionColor = .black
        inboxStyle?.dateColor = .black
         inboxStyle?.titleFont = UIFont(name: "OpenSans", size: 18.0)
        
        guard let inboxViewController = PWIInboxUI.createInboxController(with: inboxStyle) else {
            return nil
        }
        return inboxViewController
    }
```

**Comment by wfhm** [comment]
@stoyloff,

Thanks, please let me pull some time to debug the issue and I will come back to you as soon as there is any news.

**Comment by wfhm** [comment]
@stoyloff,

May I ask you to try our sample and let me know about the results?

https://github.com/Pushwoosh/pushwoosh-inbox-ui-ios-sdk/tree/master/Sample

It looks like you either use a quite outdated inbox lib version, or you had already changed something in your inbox that affects this particular functionality.

**Comment by stoyloff** [comment]
We are using.
Pushwoosh → 5.22
PushwooshInboxUI → 5.16
Which seems to be the most recent version.

**Comment by wfhm** [comment]
@stoyloff,

Did you have a chance to try the sample project? Is the issue reproducible with it? If yes, could you please provide us with a bit more details on your environment - what is the iOS version installed on the device, what is the Xcode version, which particular device is in question?
