### ISSUE TITLE
Observer for PWInbox unreadMessagesCount doesn't seem to update when app is in background

### ISSUE THREAD

**Issue by michael-seiler** [Pushwoosh/pushwoosh-inbox-ui-ios-sdk#9]
Hi, I'm developing an app with the Inbox UI. The app displays a button with a badge showing the unread messages. Therefore I register as an observer for unread messages: 
`PWInbox.addObserverForUnreadMessagesCount`
I have discovered that the number of unread messages is updated correctly as long as the app is in the foreground. However, if the app is in the background and I send a new pushmessage to the inbox, the number of unread messages is not updated until I open the Inbox. 

Is there any possibility to update the count of unread messages after the app becomes active again?

**Comment by wfhm** [comment]
@michael-seiler,

Could you please specify where and how exactly you register the observer in your code? Also, please let us know which version of Pushwoosh SDK is used and whether you use our default InboxUI solution or if you are developing your custom UI.

**Comment by michael-seiler** [comment]
@wfhm ,

the versions of the Pushwoosh sdk that we use (from Podfile.lock): 
- Pushwoosh (5.23.1):
    - Pushwoosh/Core (= 5.23.1)
  - Pushwoosh/Core (5.23.1)
  - PushwooshInboxUI (5.23.1):
    - Pushwoosh (~> 5.16)

The code is registered in the menuBar, when initially loaded: 

            PWInbox.addObserverForUnreadMessagesCount { [unowned self] (count) in
                self.setInboxLabelCount(Int(count))
            }

            PWInbox.unreadMessagesCount { [unowned self] (count, error) in
                self.setInboxLabelCount(count)
            }

We use the default InboxUI. We subclass PWIInboxViewController so that we can control the display of the navigationbar in our ViewController class. 

Do this information answer your questions? Please contact me if you need further information. 

Thanks, Michael

**Comment by wfhm** [comment]
@michael-seiler,

Thanks, please let me pull some time to check it.

**Comment by sergei4** [comment]
I have the same issue. Is there any progress with it? 
Thanks, Mikhail

**Comment by wfhm** [comment]
Fixed with 6.0.3
